Repository DawiDov/react-typescript-training, pull requests merged in 2022-07, with the labels that each got.

#26 moved pages folder
  frontend/src/index.tsx
  frontend/src/pages/App/index.tsx
  frontend/src/pages/Home/index.module.sass
  frontend/src/pages/Home/index.tsx
Labels: enhancement

#28 created layout components
  frontend/index.module.sass
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/layout/Footer/index.tsx
  frontend/src/components/layout/Header/index.tsx
  frontend/src/components/layout/Layout/index.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/pages/App/index.tsx
  frontend/src/pages/Home/index.tsx
Labels: task

#30 Login page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/auth.ts
  frontend/src/components/layout/Header/index.tsx
  frontend/src/hooks/typeStore.ts
  frontend/src/index.tsx
  frontend/src/pages/App/index.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Login/index.module.sass
  frontend/src/pages/Login/index.tsx
  frontend/src/redux/articleReducer.ts
  frontend/src/redux/store.ts
  frontend/src/redux/types.ts
Labels: bug

#33 Create login page & authentication users
  frontend/.eslintrc.json
  frontend/index.module.sass
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/auth.ts
  frontend/src/components/form/index.tsx
  frontend/src/components/layout/Header/index.tsx
  frontend/src/hooks/typeStore.ts
  frontend/src/hooks/useActions.ts
  frontend/src/models/IUser.ts
  frontend/src/pages/App/index.sass
  frontend/src/pages/App/index.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Login/index.sass
  frontend/src/pages/Login/index.tsx
  frontend/src/redux/action-creators.ts
  frontend/src/redux/articleReducer.ts
  frontend/src/redux/reducers/auth/actionCreators.ts
  frontend/src/redux/reducers/auth/index.ts
  frontend/src/redux/reducers/auth/types.ts
  frontend/src/redux/reducers/index.ts
  frontend/src/redux/store.ts
  frontend/src/utils/rules.ts
Labels: task

#35 Articles
  backend/server/article/views.py
  frontend/src/components/pagi/index.tsx
  frontend/src/components/tile/index.sass
  frontend/src/components/tile/index.tsx
  frontend/src/custom.d.ts
  frontend/src/icons/lock.png
  frontend/src/models/IUser.ts
  frontend/src/pages/Home/index.module.sass
  frontend/src/pages/Home/index.tsx
  frontend/src/redux/action-creators.ts
  frontend/src/redux/reducers/articles/actionCreators.ts
  frontend/src/redux/reducers/articles/index.ts
  frontend/src/redux/reducers/articles/types.ts
  frontend/src/redux/reducers/auth/index.ts
  frontend/src/redux/reducers/auth/types.ts
  frontend/src/redux/reducers/index.ts
Labels: task
